### ISSUE TITLE
huge size

### ISSUE THREAD

**Issue by 313364973** [alibaba/dimbin#2]
when i try 
 const data = [
           [1] 
 ]
     const bin = DIMBIN.serialize(data)

i  got  the size 29 of bin arrybuffer。so huge。

**Comment by gaomeng1900** [comment]
Sorry for my late response.
The binary data includes a fixed-size header section. Which should be at least 24 bits depending on the complexity of the data structure. 
Dimbin is designed for large and flattened data. It's natural to be not space-efficient for a small amount of data or data with a deep, complex structure.
